# Build APK trỏ tới URL ngrok hiện tại
# Cách dùng: .\scripts\build-apk-ngrok.ps1

$ErrorActionPreference = "Stop"
$Root = Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path)
$UrlFile = Join-Path $Root "ngrok-url.txt"
$AppDir = Join-Path $Root "app_web_view (1)\app_web_view"

if (-not (Test-Path $UrlFile)) {
    Write-Host "[ERROR] Chua co ngrok-url.txt. Chay truoc: .\scripts\ngrok-start.ps1" -ForegroundColor Red
    exit 1
}

$baseUrl = (Get-Content $UrlFile -Raw).Trim()
if (-not $baseUrl) {
    Write-Host "[ERROR] ngrok-url.txt rong." -ForegroundColor Red
    exit 1
}

# Gán URL ngrok vào app Flutter (generated_base_url.dart)
$GeneratedDart = Join-Path $AppDir "lib\config\generated_base_url.dart"
$dartContent = @"
// AUTO-GENERATED by scripts/ngrok-start.ps1 or scripts/build-apk-ngrok.ps1
// Do not edit manually — chạy lại script ngrok để cập nhật.
const String kGeneratedBaseUrl = '$baseUrl';

"@
Set-Content -Path $GeneratedDart -Value $dartContent -Encoding UTF8
Write-Host "Da gan BASE_URL vao app: $baseUrl" -ForegroundColor Green

$env:JAVA_HOME = "$env:LOCALAPPDATA\jdk-17"
if (-not (Test-Path "$env:JAVA_HOME\bin\java.exe")) {
    Write-Host "[WARN] JDK 17 chua cai tai $env:JAVA_HOME — Gradle co the loi neu Java mac dinh la 25+" -ForegroundColor Yellow
}

Write-Host "Build APK voi BASE_URL=$baseUrl" -ForegroundColor Cyan
Push-Location $AppDir
try {
    flutter build apk --release --dart-define=BASE_URL=$baseUrl
    $apk = Join-Path $AppDir "build\app\outputs\flutter-apk\app-release.apk"
    if (Test-Path $apk) {
        $publicApk = Join-Path $Root "api_base\utils\download\AI_Translator_v1.0.1.apk"
        Copy-Item -Path $apk -Destination $publicApk -Force
        Write-Host ""
        Write-Host "APK local: $apk" -ForegroundColor Green
        Write-Host "APK download (khi backend + ngrok chay):" -ForegroundColor Green
        Write-Host "  $baseUrl/downloads/AI_Translator_v1.0.1.apk"
        Write-Host "Server: $baseUrl"
    }
} finally {
    Pop-Location
}
