# Khởi động ngrok tunnel tới Flask (port 5055) và cập nhật .env + ngrok-url.txt
# Cách dùng: .\scripts\ngrok-start.ps1

$ErrorActionPreference = "Stop"
$Root = Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path)
$NgrokExe = Join-Path $Root "tools\ngrok.exe"
$EnvFile = Join-Path $Root "api_base\.env"
$UrlFile = Join-Path $Root "ngrok-url.txt"
$Port = 5055

if (-not (Test-Path $NgrokExe)) {
    Write-Host "[ERROR] Khong tim thay tools\ngrok.exe" -ForegroundColor Red
    Write-Host "Chay lai script cai dat hoac tai ngrok vao thu muc tools\"
    exit 1
}

# Doc NGROK_AUTHTOKEN tu .env
$authtoken = $env:NGROK_AUTHTOKEN
if (-not $authtoken -and (Test-Path $EnvFile)) {
    Get-Content $EnvFile | ForEach-Object {
        if ($_ -match '^\s*NGROK_AUTHTOKEN\s*=\s*(.+)\s*$') {
            $authtoken = $Matches[1].Trim().Trim('"').Trim("'")
        }
    }
}

if (-not $authtoken) {
    Write-Host ""
    Write-Host "=== CAN NGROK AUTHTOKEN ===" -ForegroundColor Yellow
    Write-Host "1. Dang ky mien phi: https://dashboard.ngrok.com/signup"
    Write-Host "2. Lay token: https://dashboard.ngrok.com/get-started/your-authtoken"
    Write-Host "3. Them vao api_base\.env:"
    Write-Host "   NGROK_AUTHTOKEN=your_token_here"
    Write-Host ""
    exit 1
}

& $NgrokExe config add-authtoken $authtoken 2>$null | Out-Null

# Dung ngrok cu neu dang chay
Get-Process -Name "ngrok" -ErrorAction SilentlyContinue | Stop-Process -Force -ErrorAction SilentlyContinue
Start-Sleep -Seconds 1

Write-Host "Dang khoi dong ngrok tunnel -> 127.0.0.1:$Port ..." -ForegroundColor Cyan
Start-Process -FilePath $NgrokExe -ArgumentList "http", "127.0.0.1:$Port" -WindowStyle Normal

# Doi tunnel san sang
$publicUrl = $null
for ($i = 0; $i -lt 20; $i++) {
    Start-Sleep -Seconds 1
    try {
        $resp = Invoke-RestMethod -Uri "http://127.0.0.1:4040/api/tunnels" -TimeoutSec 3
        $tunnel = $resp.tunnels | Where-Object { $_.public_url -like "https://*" } | Select-Object -First 1
        if ($tunnel) {
            $publicUrl = $tunnel.public_url.TrimEnd('/')
            break
        }
    } catch {
        # chua san sang
    }
}

if (-not $publicUrl) {
    Write-Host "[ERROR] Khong lay duoc URL ngrok. Kiem tra cua so ngrok." -ForegroundColor Red
    exit 1
}

$redirectUri = "$publicUrl/api/auth/google/callback"
Set-Content -Path $UrlFile -Value $publicUrl -Encoding UTF8

# Gán URL ngrok vào app Flutter
$AppDir = Join-Path $Root "app_web_view (1)\app_web_view"
$GeneratedDart = Join-Path $AppDir "lib\config\generated_base_url.dart"
$dartContent = @"
// AUTO-GENERATED by scripts/ngrok-start.ps1 or scripts/build-apk-ngrok.ps1
// Do not edit manually — chạy lại script ngrok để cập nhật.
const String kGeneratedBaseUrl = '$publicUrl';

"@
Set-Content -Path $GeneratedDart -Value $dartContent -Encoding UTF8

# Cap nhat api_base/.env
if (Test-Path $EnvFile) {
    $lines = Get-Content $EnvFile
    $newLines = @()
    $foundRedirect = $false
    $foundFrontend = $false

    foreach ($line in $lines) {
        if ($line -match '^\s*GOOGLE_REDIRECT_URI\s*=') {
            $newLines += "GOOGLE_REDIRECT_URI=$redirectUri"
            $foundRedirect = $true
        } elseif ($line -match '^\s*FRONTEND_URL\s*=') {
            $newLines += "FRONTEND_URL=$publicUrl"
            $foundFrontend = $true
        } else {
            $newLines += $line
        }
    }
    if (-not $foundRedirect) { $newLines += "GOOGLE_REDIRECT_URI=$redirectUri" }
    if (-not $foundFrontend) { $newLines += "FRONTEND_URL=$publicUrl" }

    Set-Content -Path $EnvFile -Value $newLines -Encoding UTF8
}

Write-Host ""
Write-Host "========================================" -ForegroundColor Green
Write-Host "  NGROK DA SAN SANG" -ForegroundColor Green
Write-Host "========================================" -ForegroundColor Green
Write-Host ""
Write-Host "Public URL:  $publicUrl" -ForegroundColor Cyan
Write-Host "OAuth URI:   $redirectUri" -ForegroundColor Cyan
Write-Host ""
Write-Host "BUOC TIEP THEO:" -ForegroundColor Yellow
Write-Host "1. Khoi dong lai backend (python run_api.py) de ap dung .env moi"
Write-Host "2. Google Cloud Console -> OAuth Client -> them redirect URI:"
Write-Host "   $redirectUri"
Write-Host "3. Build APK:"
Write-Host "   .\scripts\build-apk-ngrok.ps1"
Write-Host ""
Write-Host "URL da luu vao: ngrok-url.txt"
Write-Host ""
